#!/bin/bash
f=IOP_HEPP_Conference_presentation_London_3rd_April_2023
if pdflatex $f.tex
then
  cd fgraph
  MPFILES=`ls *.mp`
  for MP in ${MPFILES}; do
    mpost ${MP}
  done
  cd ..
  pdflatex $f.tex
fi
rm $f.{aux,log,nav,out,snm,toc,vrb}
